---
title: Debarulers
baseline: Your blogging assistant
description: A ready to use static blog, powered by Cecil.
baseurl: "/"
canonicalurl: true
keywords:
- Cecil
- Static Site Generator
- SSG
author: Nicolas B
date:
  format: j F Y
  timezone: Europe/Paris
theme: []
hyde:
  sidebar:
    sticky: true
  theme: ''
  reverse: false
