baseURL = 'https://Nikill.github.io/debarulers/'

languageCode = 'fr'
title = 'Debarulers'
theme = 'hugo-music'
defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = false
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[languages]
  [languages.fr]
    languageName = 'Français'
    weight = 1
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = 'home'
        name = 'Accueil'
        url = ''
        weight = 1
      [[languages.fr.menu.main]]
        identifier = 'music'
        name = 'Musique'
        url = 'musique/'
        weight = 2
      [[languages.fr.menu.main]]
        identifier = 'concerts'
        name = 'Concerts'
        url = 'concerts/'
        weight = 3
      [[languages.fr.menu.main]]
        identifier = 'rider'
        name = 'Technical Rider'
        url = 'technical-rider/'
        weight = 4
      [[languages.fr.menu.main]]
        identifier = 'contact'
        name = 'Contact'
        url = 'contact/'
        weight = 5
  [languages.en]
    languageName = 'English'
    weight = 2
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = 'home'
        name = 'Home'
        url = ''
        weight = 1
      [[languages.en.menu.main]]
        identifier = 'music'
        name = 'Music'
        url = 'music/'
        weight = 2
      [[languages.en.menu.main]]
        identifier = 'concerts'
        name = 'Concerts'
        url = 'concerts/'
        weight = 3
      [[languages.en.menu.main]]
        identifier = 'rider'
        name = 'Technical Rider'
        url = 'technical-rider/'
        weight = 4
      [[languages.en.menu.main]]
        identifier = 'contact'
        name = 'Contact'
        url = 'contact/'
        weight = 5
